services:
  eotdl-qdrant:
    image: qdrant/qdrant:latest
    container_name: eotdl-qdrant
    ports:
      - 6333:6333
      - 6334:6334
    volumes:
      - ./data/qdrant:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
    restart: unless-stopped

  eotdl-mcp:
    build: ./mcp
    container_name: eotdl-mcp
    ports:
      - 8001:8000
    environment:
      - QDRANT_URL=http://eotdl-qdrant:6333
      - QDRANT_API_KEY=
    volumes:
      - ./mcp/server.py:/server.py
    depends_on:
      - eotdl-qdrant
    command: uv run server.py --host 0.0.0.0 --port 8000
